/**
 * Mock Data
 * Static mock data for development and testing
 */

import { Flight } from "./types";

export const flights: Flight[] = [
  // DAC-NYC (2 flights)
  {
    id: "1",
    airline: "Air Example",
    origin: "DAC",
    destination: "NYC",
    discountedPrice: 599,
    prevPrice: 750,
    coupon: "SAVE20",
    duration: "16h 30m",
    departureTime: "08:00",
    arrivalTime: "00:30",
  },
  {
    id: "2",
    airline: "Sky Airways",
    origin: "DAC",
    destination: "NYC",
    discountedPrice: 649,
    prevPrice: 800,
    coupon: "FLY15",
    duration: "15h 45m",
    departureTime: "14:30",
    arrivalTime: "06:15",
  },
  // NYC-LON (3 flights)
  {
    id: "3",
    airline: "Global Airlines",
    origin: "NYC",
    destination: "LON",
    discountedPrice: 379,
    prevPrice: 450,
    coupon: "GLOBAL10",
    duration: "7h 00m",
    departureTime: "18:00",
    arrivalTime: "01:00",
  },
  {
    id: "4",
    airline: "United Express",
    origin: "NYC",
    destination: "LON",
    discountedPrice: 425,
    prevPrice: 500,
    coupon: "UNITED25",
    duration: "6h 50m",
    departureTime: "22:30",
    arrivalTime: "05:20",
  },
  {
    id: "5",
    airline: "Delta Connect",
    origin: "NYC",
    destination: "LON",
    discountedPrice: 389,
    prevPrice: 480,
    coupon: "DELTA15",
    duration: "7h 15m",
    departureTime: "10:00",
    arrivalTime: "17:15",
  },
  // LON-PAR (1 flight)
  {
    id: "6",
    airline: "JetBlue",
    origin: "LON",
    destination: "PAR",
    discountedPrice: 159,
    prevPrice: 200,
    coupon: "BLUE20",
    duration: "1h 20m",
    departureTime: "09:15",
    arrivalTime: "10:35",
  },
  // PAR-DXB (2 flights)
  {
    id: "7",
    airline: "American Airlines",
    origin: "PAR",
    destination: "DXB",
    discountedPrice: 499,
    prevPrice: 620,
    coupon: "AMERICAN18",
    duration: "7h 25m",
    departureTime: "11:30",
    arrivalTime: "18:55",
  },
  {
    id: "8",
    airline: "Alaska Airlines",
    origin: "PAR",
    destination: "DXB",
    discountedPrice: 535,
    prevPrice: 650,
    coupon: "ALASKA12",
    duration: "7h 10m",
    departureTime: "15:00",
    arrivalTime: "22:10",
  },
  // DXB-TYO (3 flights)
  {
    id: "9",
    airline: "Spirit Airlines",
    origin: "DXB",
    destination: "TYO",
    discountedPrice: 699,
    prevPrice: 850,
    coupon: "SPIRIT30",
    duration: "9h 30m",
    departureTime: "02:20",
    arrivalTime: "11:50",
  },
  {
    id: "10",
    airline: "Frontier",
    origin: "DXB",
    destination: "TYO",
    discountedPrice: 729,
    prevPrice: 900,
    coupon: "FRONT15",
    duration: "9h 10m",
    departureTime: "08:45",
    arrivalTime: "17:55",
  },
  {
    id: "11",
    airline: "Hawaiian Airlines",
    origin: "DXB",
    destination: "TYO",
    discountedPrice: 759,
    prevPrice: 920,
    coupon: "HAWAII22",
    duration: "9h 05m",
    departureTime: "13:30",
    arrivalTime: "22:35",
  },
  // TYO-SYD (2 flights)
  {
    id: "12",
    airline: "Air Example",
    origin: "TYO",
    destination: "SYD",
    discountedPrice: 549,
    prevPrice: 680,
    coupon: "SAVE15",
    duration: "9h 45m",
    departureTime: "10:00",
    arrivalTime: "19:45",
  },
  {
    id: "13",
    airline: "Sky Airways",
    origin: "TYO",
    destination: "SYD",
    discountedPrice: 589,
    prevPrice: 720,
    coupon: "FLY20",
    duration: "9h 30m",
    departureTime: "16:30",
    arrivalTime: "02:00",
  },
  // SYD-SIN (1 flight)
  {
    id: "14",
    airline: "Global Airlines",
    origin: "SYD",
    destination: "SIN",
    discountedPrice: 379,
    prevPrice: 460,
    coupon: "GLOBAL10",
    duration: "8h 00m",
    departureTime: "12:15",
    arrivalTime: "20:15",
  },
  // SIN-BKK (3 flights)
  {
    id: "15",
    airline: "United Express",
    origin: "SIN",
    destination: "BKK",
    discountedPrice: 199,
    prevPrice: 250,
    coupon: "UNITED25",
    duration: "2h 30m",
    departureTime: "07:30",
    arrivalTime: "10:00",
  },
  {
    id: "16",
    airline: "Delta Connect",
    origin: "SIN",
    destination: "BKK",
    discountedPrice: 189,
    prevPrice: 240,
    coupon: "DELTA15",
    duration: "2h 25m",
    departureTime: "12:00",
    arrivalTime: "14:25",
  },
  {
    id: "17",
    airline: "JetBlue",
    origin: "SIN",
    destination: "BKK",
    discountedPrice: 209,
    prevPrice: 260,
    coupon: "BLUE20",
    duration: "2h 35m",
    departureTime: "18:15",
    arrivalTime: "20:50",
  },
  // BKK-CCU (2 flights)
  {
    id: "18",
    airline: "American Airlines",
    origin: "BKK",
    destination: "CCU",
    discountedPrice: 299,
    prevPrice: 380,
    coupon: "AMERICAN18",
    duration: "3h 25m",
    departureTime: "09:30",
    arrivalTime: "12:55",
  },
  {
    id: "19",
    airline: "Alaska Airlines",
    origin: "BKK",
    destination: "CCU",
    discountedPrice: 319,
    prevPrice: 400,
    coupon: "ALASKA12",
    duration: "3h 30m",
    departureTime: "15:00",
    arrivalTime: "18:30",
  },
  // CCU-DAC (1 flight)
  {
    id: "20",
    airline: "Spirit Airlines",
    origin: "CCU",
    destination: "DAC",
    discountedPrice: 129,
    prevPrice: 180,
    coupon: "SPIRIT30",
    duration: "1h 10m",
    departureTime: "14:20",
    arrivalTime: "15:30",
  },
  // LON-DAC (1 flight)
  {
    id: "21",
    airline: "Frontier",
    origin: "LON",
    destination: "DAC",
    discountedPrice: 529,
    prevPrice: 650,
    coupon: "FRONT15",
    duration: "10h 30m",
    departureTime: "20:45",
    arrivalTime: "07:15",
  },
  // DXB-NYC (3 flights)
  {
    id: "22",
    airline: "Hawaiian Airlines",
    origin: "DXB",
    destination: "NYC",
    discountedPrice: 759,
    prevPrice: 920,
    coupon: "HAWAII22",
    duration: "14h 05m",
    departureTime: "03:30",
    arrivalTime: "17:35",
  },
  {
    id: "23",
    airline: "Air Example",
    origin: "DXB",
    destination: "NYC",
    discountedPrice: 799,
    prevPrice: 950,
    coupon: "SAVE15",
    duration: "13h 50m",
    departureTime: "10:00",
    arrivalTime: "23:50",
  },
  {
    id: "24",
    airline: "Sky Airways",
    origin: "DXB",
    destination: "NYC",
    discountedPrice: 829,
    prevPrice: 1000,
    coupon: "FLY20",
    duration: "14h 15m",
    departureTime: "16:30",
    arrivalTime: "06:45",
  },
];

export const DESTINATIONS: { value: string; label: string }[] = [
  { value: "DAC", label: "Dhaka, Bangladesh" },
  { value: "NYC", label: "New York, USA" },
  { value: "LON", label: "London, UK" },
  { value: "PAR", label: "Paris, France" },
  { value: "DXB", label: "Dubai, UAE" },
  { value: "TYO", label: "Tokyo, Japan" },
  { value: "SYD", label: "Sydney, Australia" },
  { value: "SIN", label: "Singapore" },
  { value: "BKK", label: "Bangkok, Thailand" },
  { value: "CCU", label: "Kolkata, India" },
];
